[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | tmp
  )/
  | manage.py
)
'''

[tool.isort]
profile = "black"
line_length = 120
force_single_line = true
skip = ['migrations', 'settings', 'settings.py']
balanced_wrapping = true
known_django = 'django'
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "rich_trader.settings.test"
python_files = ["test_*.py", "*_test.py"]
addopts = [
  "--import-mode=importlib",
  "--no-migrations",
  "--exitfirst",
  "--no-cov-on-fail",
  "--cov=core",
  "--cov=rich",
  "--cov=rich_trader",
  "--cov=accounts"
]

[tool.coverage.run]
omit = [
    "manage.py",
    "conftest.py",
    "factories/*",
    "*/tests.py",
    "*/tests/*",
    "*/settings/*.py",
    "*/migrations/*.py",
    "*/asgi.py",
    "*/wsgi.py"
]

[tool.coverage.report]
show_missing = true
precision = 2
skip_empty = true

# PyLance bug: https://github.com/microsoft/pylance-release/issues/3366
[tool.pyright]
