# Generated by Django 5.0.4 on 2024-05-10 12:39

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('txid', models.CharField(max_length=50)),
                ('pair', models.CharField(max_length=20)),
                ('trade_at', models.DateTimeField()),
                ('order_type', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('volume', models.FloatField()),
                ('fee', models.FloatField()),
                ('margin', models.FloatField()),
                ('misc', models.CharField(max_length=50)),
                ('closing', models.CharField(max_length=50)),
                ('raw', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
