# Generated by Django 5.0.4 on 2024-05-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='closing',
        ),
    ]
