# Generated by Django 5.0.4 on 2024-05-11 13:12

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0002_remove_trade_closing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('data_at', models.DateTimeField()),
                ('rank', models.IntegerField()),
                ('circulating_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('max_supply', models.FloatField()),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('change_1h', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('change_7d', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('raw', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
