# Generated by Django 5.0.4 on 2024-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0003_cryptolisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptolisting',
            name='max_supply',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
