# Generated by Django 5.1.4 on 2024-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_tradingconfig_target_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltradingconfig',
            name='max_amount',
            field=models.PositiveIntegerField(default=30000, help_text='Maximum amount in KRW to invest'),
        ),
        migrations.AddField(
            model_name='historicaltradingconfig',
            name='min_amount',
            field=models.PositiveIntegerField(default=5000, help_text='Minimum amount in KRW to invest'),
        ),
        migrations.AddField(
            model_name='historicaltradingconfig',
            name='step_amount',
            field=models.PositiveIntegerField(default=5000, help_text='Step amount in KRW for investment increments'),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='max_amount',
            field=models.PositiveIntegerField(default=30000, help_text='Maximum amount in KRW to invest'),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='min_amount',
            field=models.PositiveIntegerField(default=5000, help_text='Minimum amount in KRW to invest'),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='step_amount',
            field=models.PositiveIntegerField(default=5000, help_text='Step amount in KRW for investment increments'),
        ),
    ]
