# Generated by Django 5.1.4 on 2024-12-29 14:52

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_historicaltradingconfig_max_coins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order_id', models.CharField(max_length=255)),
                ('coin', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, help_text='주문 금액 (KRW)', max_digits=13)),
                ('type', models.CharField(help_text='주문 유형 (예: MARKET)', max_length=20)),
                ('side', models.CharField(help_text='BUY/SELL', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=0, help_text='거래 수수료 (KRW)', max_digits=13)),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='주문 가격 (KRW)', max_digits=13, null=True)),
                ('fee_rate', models.DecimalField(blank=True, decimal_places=4, help_text='수수료율 (%)', max_digits=5, null=True)),
                ('average_fee_rate', models.DecimalField(blank=True, decimal_places=4, help_text='평균 수수료율 (%)', max_digits=5, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=0, help_text='체결 가격 한도 (KRW)', max_digits=13, null=True)),
                ('original_qty', models.DecimalField(blank=True, decimal_places=8, help_text='최초 주문 수량 (코인)', max_digits=17, null=True)),
                ('executed_qty', models.DecimalField(blank=True, decimal_places=8, help_text='체결된 수량 (코인)', max_digits=17, null=True)),
                ('canceled_qty', models.DecimalField(blank=True, decimal_places=8, help_text='취소된 수량 (코인)', max_digits=17, null=True)),
                ('traded_amount', models.DecimalField(blank=True, decimal_places=0, help_text='실제 거래된 금액 (KRW)', max_digits=13, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=0, help_text='원래 주문 금액 (KRW)', max_digits=13, null=True)),
                ('canceled_amount', models.DecimalField(blank=True, decimal_places=0, help_text='취소된 금액 (KRW)', max_digits=13, null=True)),
                ('order_detail', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
