# Generated by Django 5.1.4 on 2024-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='average_executed_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='평균 체결 가격 (KRW)', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='canceled_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='주문 취소 총액', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='주문 총액', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='traded_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='체결된 총액', max_digits=13, null=True),
        ),
    ]
