# Generated by Django 5.1.4 on 2024-12-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trading_average_executed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='주문 금액 (KRW)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='trading',
            name='average_executed_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='평균 체결 가격 (KRW)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='canceled_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='주문 취소 총액', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='fee',
            field=models.DecimalField(decimal_places=0, help_text='거래 수수료 (KRW)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='trading',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='체결 가격 한도 (KRW)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='주문 총액', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='주문 가격 (KRW)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='traded_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='체결된 총액', max_digits=20, null=True),
        ),
    ]
