# Generated by Django 5.1.4 on 2024-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_trading_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='체크하면 자동 매수가 활성화됩니다', verbose_name='자동 매수 활성화'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='max_amount',
            field=models.PositiveIntegerField(default=30000, help_text='한 번에 매수할 최대 금액 (원)', verbose_name='최대 매수금액'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='max_coins',
            field=models.PositiveSmallIntegerField(default=2, help_text='한 번에 추천할 최대 코인 개수', verbose_name='최대 코인 개수'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='min_amount',
            field=models.PositiveIntegerField(default=5000, help_text='한 번에 매수할 최소 금액 (원)', verbose_name='최소 매수금액'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=1, help_text='한 번에 추천할 최소 코인 개수 (0은 제한 없음)', verbose_name='최소 코인 개수'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='step_amount',
            field=models.PositiveIntegerField(default=5000, help_text='매수금액의 증가 단위 (원)', verbose_name='매수금액 단위'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='체크하면 자동 매수가 활성화됩니다', verbose_name='자동 매수 활성화'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='max_amount',
            field=models.PositiveIntegerField(default=30000, help_text='한 번에 매수할 최대 금액 (원)', verbose_name='최대 매수금액'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='max_coins',
            field=models.PositiveSmallIntegerField(default=2, help_text='한 번에 추천할 최대 코인 개수', verbose_name='최대 코인 개수'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='min_amount',
            field=models.PositiveIntegerField(default=5000, help_text='한 번에 매수할 최소 금액 (원)', verbose_name='최소 매수금액'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=1, help_text='한 번에 추천할 최소 코인 개수 (0은 제한 없음)', verbose_name='최소 코인 개수'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='step_amount',
            field=models.PositiveIntegerField(default=5000, help_text='매수금액의 증가 단위 (원)', verbose_name='매수금액 단위'),
        ),
    ]
