# Generated by Django 5.1.4 on 2024-12-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_historicaltradingconfig_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=1, help_text='한 번에 추천할 최소 코인 개수 (0은 매수 추천이 없을 수 있음)', verbose_name='최소 코인 개수'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=1, help_text='한 번에 추천할 최소 코인 개수 (0은 매수 추천이 없을 수 있음)', verbose_name='최소 코인 개수'),
        ),
    ]
