# Generated by Django 5.1.4 on 2025-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_historicaltradingconfig_min_trade_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=1, help_text='한 번에 추천할 최소 코인 개수 (0은 거래 추천이 없을 수 있음)', verbose_name='최소 코인 개수'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='min_trade_amount',
            field=models.PositiveIntegerField(default=5000, help_text='거래당 최소 금액 (원)', verbose_name='최소 거래금액'),
        ),
        migrations.AlterField(
            model_name='historicaltradingconfig',
            name='step_amount',
            field=models.PositiveIntegerField(default=5000, help_text='거래금액의 증가 단위 (원)', verbose_name='거래금액 단위'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='min_coins',
            field=models.SmallIntegerField(default=1, help_text='한 번에 추천할 최소 코인 개수 (0은 거래 추천이 없을 수 있음)', verbose_name='최소 코인 개수'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='min_trade_amount',
            field=models.PositiveIntegerField(default=5000, help_text='거래당 최소 금액 (원)', verbose_name='최소 거래금액'),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='step_amount',
            field=models.PositiveIntegerField(default=5000, help_text='거래금액의 증가 단위 (원)', verbose_name='거래금액 단위'),
        ),
    ]
