# Generated by Django 5.1.4 on 2025-01-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_historicaltradingconfig_min_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='reason',
            field=models.TextField(blank=True, help_text='주문 사유', null=True),
        ),
    ]
